openapi: 3.0.0
info:
  title: API de Gestão de IPs
  version: 1.0.0
paths:
  /gestion:
    post:
      summary: Processa um arquivo JSON com endereços IP
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: Arquivo JSON com endereços IP
      responses:
        '200':
          description: Processamento concluído
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Erro na requisição
